name: do upload ia

on:
  workflow_dispatch:
    inputs:
      query:
        description: query

env:
  PASSWORD: ${{ secrets.FRT_DECIPHER }}
  SYNAPSE_CONFIG: detect this
  FRT_MAKE_TEMP_SYMLINK: "yes"
  REPO: "github,bitbucket"
  VIDEOS_ENDPOINT: "github"
  ENABLE_SIA_RELATIONS: "no"
  GIT_COPY_MODE: "actions"
  FRT_GIT_PUSH_SPEED: "10.0"
  DOCKER_REPLICA_USE_ACTIONS: "yes"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone code
      run: git clone ${{ secrets.FRT_CLONE }} gh
    - name: Set up Tailscale
      continue-on-error: true
      uses: tailscale/github-action@main
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        version: "1.16.1"
    - name: Add SSH key
      continue-on-error: true
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        MACHINE: misc1
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan "$(tailscale ip -6 $MACHINE)" >> ~/.ssh/known_hosts
        printf "%s" "$SSH_KEY" > ~/.ssh/key
        chmod 600 ~/.ssh/key
        ssh -i $HOME/.ssh/key -fND 1720 lesmi@"$(tailscale ip -6 $MACHINE)"
        echo "IA_REPLICA_SOCKS5_PROXY=localhost:1720" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: gh
    - name: Build with Gradle
      run: ./gradlew fJ &>/dev/null
      working-directory: gh
    - name: Build with Gradle
      run: ./gradlew rAM
      working-directory: gh
    - name: Run code
      run: java -cp ./build/libs/FileReadingTester-1.0-SNAPSHOT-all.jar frt.replicas.ia.InternetArchiveUploadSatelliteKt ${{ github.event.inputs.query }}
      working-directory: gh
